# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f75b7eded8fb01c619016dd36473c63de642a6daebcb339764a2ca80672e71616707a6ac0051f79e3d8fa127ea230659eedb98eb53f2e581f0dd20aed9a6375d

test:
  secret_key_base: df04509503c991bbd495b608fdee349e068822364c15c127934058420f114d6d4b435a5f6abd10b198bbc277a91acae68966e6406dd242e7ddac906b49262a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
